### ISSUE TITLE
Difference with binauralFIR?

### ISSUE THREAD

**Issue by mattdesl** [Ircam-RnD/binauralModeled#1]
Might be worth documenting how this differs from the other module. I am unclear about the differences. 

Thanks for all the open source! 😄👍

**Comment by ouhouhsami** [comment]
Hi, 

one (the FIR) is a "real" HRTF file convolved with the input signal, the other (the modeled one) is modeled using some coefficient that go throught a fractional delay and biquad filter.

The modeled one is using scriptprocessor node, whereas the FIR one is using exclusively non scriptprocessor nodes.

Best,

**Comment by mattdesl** [comment]
Thanks :smile:
